---
services: [docker]
language: python
env:
  global:
    - |
      RELEASE_DEBUG="" \
      NBPARALLEL="2" \
      DO_RELEASE="1" \
      RELEASABLE_REPOS="corpusops/" \
      COPS_URL="https://github.com/corpusops/corpusops.bootstrap" \
      COPS_ROOT="$TRAVIS_BUILD_DIR/local/corpusops.bootstrap" \
      funcs="$COPS_ROOT/bin/cops_shell_common" \
      silent="$funcs output_in_error silent_vv" \
      apply_role="sudo -E $silent $COPS_ROOT/bin/cops_apply_role -vvvvv" \
      install="sudo -E $silent $COPS_ROOT/bin/install.sh" \
      sync_code="$install -C --synchronize-code --skip-sync-core" \
      release="$COPS_ROOT/hacking/docker_release" \
      silent_rm="$silent rm -rf"
  matrix:
  - IMAGES="corpusops/ovh-backup"
cache: {directories: ["$HOME/.cache/pip", "$COPS_ROOT", "/var/lib/docker"]}
#before_install:
#- sudo apt-get update -qq
#- sudo apt-get install -qq -y --force-yes parallel
#- sudo service docker stop
#- sh -c ": &&    .ansible/scripts/download_corpusops.sh"
#- sh -c "$silent .ansible/scripts/setup_corpusops.sh"
#- sh -c "$apply_role */*/roles/corpusops.roles/services_virt_docker/role.yml"
#- i=$(whoami) && sudo chown -Rf $i $COPS_ROOT
#- cd "$TRAVIS_BUILD_DIR"
#script:
#- echo "building $IMAGES" >&2
#- docker-compose -f docker-compose.yml -f docker-compose-build.yml build
#- DO_RELEASE=1 $release
